### ISSUE TITLE
Missing Positional Argument

### ISSUE THREAD

**Issue by SquashyDisco** [openraildata/td-trust-example-python3#1]
Heya, I'm teaching myself Python and I'm trying to get my head around it as a newbie.

Previously, I had this working but I can't seem to understand where I'm going wrong after I've re-installed my OS. 

When I use the example command  - _source venv/bin/activate
./main.py --td)__

I keep getting the following issue:

Traceback (most recent call last):
  File "xxx/td-trust-example-python3/./main.py", line 70, in <module>
    connection.connect(**connect_headers)
  File "xxx/td-trust-example-python3/venv/lib/python3.10/site-packages/stomp/connect.py", line 150, in connect
    self.transport.start()
  File "xxx/td-trust-example-python3/venv/lib/python3.10/site-packages/stomp/transport.py", line 125, in start
    self.attempt_connection()
  File "xxx/td-trust-example-python3/venv/lib/python3.10/site-packages/stomp/transport.py", line 755, in attempt_connection
    self.__enable_keepalive()
  File "xxx/td-trust-example-python3/venv/lib/python3.10/site-packages/stomp/transport.py", line 733, in __enable_keepalive
    try_setsockopt(self.socket, socket.IPPROTO_TCP, 0x10, ka_intvl)
TypeError: Transport.__enable_keepalive.<locals>.try_setsockopt() missing 1 required positional argument: 'val'

Are you able to help a beginner?!

**Comment by SquashyDisco** [comment]
Fixed, Stomp.py needs to be updated to 8.1.0 in the requirements

**Comment by EvelynSubarrow** [comment]
Hello, very sorry I didn't reply to this earlier (I really need to change my primary email address). Glad to see you've worked out a fix. For your last post, do you mean that you updated stomp to 8.0.1 as in requirements (i.e. this was a mistake on your end), or that 8.0.1 wasn't working and you had to upgrade to 8.1.0? (i.e. I'd still need to upgrade the dependency)

**Comment by SquashyDisco** [comment]
Hey, 8.0.1 wasn't working and I had to upgrade to 8.1.0
